apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ if .Values.serviceAccount.name }}{{ .Values.serviceAccount.name }}{{ else }}{{ .Release.Name }}-sample-service{{ end }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name | default "sample-service" }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- if .Values.serviceAccount.annotations }}
  annotations:
{{ toYaml .Values.serviceAccount.annotations | indent 4 }}
{{- end }}
